server:
  port: 8090

jwt:
  secret: 52eb537d29b2f4983a2a7c8e1786ae7d7968aaa3cf4fff366ec938f15164a584d078a86e173bb5f44e69cb40e8531a797a70a53404df73c2d182d9e5066f087f3903ec602b29c9fb3823059f4179e8339ea968ab380971d0fcdd3ec2c89d0da0c6f0376f0233dc857e96de510b3ec4621739205718c3448779c91980da3eaf77e1938ebe5657113dedad07e20e093ef5d773624b71865f7199bda126142f30ab7fe34f6ce145ad7b9c2f74d5538b231a9afb7dfa5965bb5827df848c3745c0bc8ece893a8333edc9fed7ae3608d28bb7ccc73ee9c1a9e88d42695d92982ad0efaa6a3172e9f98f5d3ab1fe03b589a7966bb51a8d027e4b416e31b668f4d43d10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowed-origins:
              - "http://localhost:8093"
              - "http://192.168.1.13:19006"
              - "exp://192.168.1.13:19000"
              - "http://192.168.1.13:19006"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - DELETE
                  - POST

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/products/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - POST
                  - PUT
                  - DELETE

        - id: category-service
          uri: lb://productservice
          predicates:
            - Path=/categories/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - POST
                  - PUT
                  - DELETE

        - id: promotion-service
          uri: lb://productservice
          predicates:
            - Path=/promotions/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - POST
                  - PUT
                  - DELETE

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - DELETE
                  - PUT

        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/stores/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - POST
                  - PUT
                  - DELETE

        - id: store-stock-service
          uri: lb://store-service
          predicates:
            - Path=/stores/**
          filters:
            - name: Authentication
              args:
                requiredRoles:
                  - ROLE_ADMIN
                securedMethods:
                  - POST
                  - PUT
                  - DELETE

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
          filters:
            - name: Authentication

        - id: wishlist-endpoints
          uri: lb://cart-service
          predicates:
            - Path=/wishlist/**
          filters:
            - name: Authentication

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: Authentication

        - id: stripe-endpoints
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: Authentication
